/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    Components: typeof import('./components/index.tsx')['default']
    Demo1: typeof import('./components/Demo1.vue')['default']
    Demo2: typeof import('./components/Demo2.tsx')['default']
    HelloWorld: typeof import('./components/HelloWorld.tsx')['default']
    IMaterialSymbols2k: typeof import('~icons/material-symbols/2k')['default']
  }
}
